package com.example.favoritedoggies.home

import com.example.data.model.breed.AllBreedsResponse
import com.example.data.model.breed.Breeds

object MockAllBreedsResponse {

    private fun mockBreeds(): Breeds {
        return Breeds(
            affenpinscher = listOf("sub1", "sub2"),
            african = emptyList(),
            airedale = listOf("sub1"),
            akita = listOf("sub1"),
            appenzeller = emptyList(),
            australian = listOf("sub1", "sub2"),
            bakharwal = emptyList(),
            basenji = emptyList(),
            beagle = listOf("sub1"),
            bluetick = listOf("sub1", "sub2"),
            borzoi = emptyList(),
            bouvier = emptyList(),
            boxer = listOf("sub1"),
            brabancon = emptyList(),
            briard = emptyList(),
            buhund = emptyList(),
            bulldog = listOf("sub1", "sub2"),
            bullterrier = emptyList(),
            cattledog = emptyList(),
            cavapoo = emptyList(),
            chihuahua = listOf("sub1"),
            chippiparai = emptyList(),
            chow = emptyList(),
            clumber = emptyList(),
            cockapoo = emptyList(),
            collie = listOf("sub1"),
            coonhound = emptyList(),
            corgi = emptyList(),
            cotondetulear = emptyList(),
            dachshund = listOf("sub1"),
            dalmatian = listOf("sub1"),
            dane = listOf("sub1"),
            danish = listOf("sub1"),
            deerhound = listOf("sub1"),
            dhole = emptyList(),
            dingo = listOf("sub1"),
            doberman = emptyList(),
            elkhound = emptyList(),
            entlebucher = emptyList(),
            eskimo = emptyList(),
            finnish = listOf("sub1"),
            frise = listOf("sub1"),
            gaddi = emptyList(),
            germanshepherd = listOf("sub1"),
            greyhound = emptyList(),
            groenendael = emptyList(),
            havanese = emptyList(),
            hound = listOf("sub1"),
            husky = emptyList(),
            keeshond = emptyList(),
            kelpie = listOf("sub1"),
            kombai = emptyList(),
            komondor = listOf("sub1"),
            kuvasz = emptyList(),
            labradoodle = listOf("sub1"),
            labrador = listOf("sub1"),
            leonberg = emptyList(),
            lhasa = emptyList(),
            malamute = listOf("sub1"),
            malinois = listOf("sub1"),
            maltese = emptyList(),
            mastiff = listOf("sub1"),
            mexicanhairless = emptyList(),
            mix = emptyList(),
            mountain = emptyList(),
            mudhol = emptyList(),
            newfoundland = listOf("sub1"),
            otterhound = emptyList(),
            ovcharka = emptyList(),
            papillon = emptyList(),
            pariah = listOf("sub1"),
            pekinese = listOf("sub1"),
            pembroke = emptyList(),
            pinscher = listOf("sub1"),
            pitbull = emptyList(),
            pointer = listOf("sub1"),
            pomeranian = listOf("sub1"),
            poodle = listOf("sub1"),
            pug = emptyList(),
            puggle = emptyList(),
            pyrenees = emptyList(),
            rajapalayam = emptyList(),
            redbone = listOf("sub1"),
            retriever = listOf("sub1"),
            ridgeback = listOf("sub1"),
            rottweiler = listOf("sub1"),
            saluki = listOf("sub1"),
            samoyed = emptyList(),
            schipperke = emptyList(),
            schnauzer = emptyList(),
            segugio = emptyList(),
            setter = emptyList(),
            sharpei = listOf("sub1"),
            sheepdog = emptyList(),
            shiba = listOf("sub1"),
            shihtzu = emptyList(),
            spaniel = listOf("sub1"),
            spitz = emptyList(),
            springer = emptyList(),
            stbernard = listOf("sub1"),
            terrier = listOf("sub1"),
            tervuren = emptyList(),
            vizsla = emptyList(),
            waterdog = emptyList(),
            weimaraner = listOf("sub1"),
            whippet = emptyList(),
            wolfhound = emptyList()
        )
    }

    fun mockAllBreedsResponse(): AllBreedsResponse {
        return AllBreedsResponse(
            message = mockBreeds(),
            status = "success"
        )
    }
}